name: weixin

on:

  workflow_dispatch:

    branches:

      - master

  schedule:

    # `分 时 天 月 周` 时按照标准时间 北京时间=标准时间+8 18表示北京时间早上2点

    - cron: '40 23 * * *'

jobs:

#将工作流程中运行的所有作业组合在一起

  build:

  #定义名为 build 的作业。 子键将定义作业的属性 

    runs-on: ubuntu-latest 

    steps:

      - uses: actions/checkout@v2

    

      - name: Set up Python 3.9

        uses: actions/setup-python@v2

        with:

          python-version: 3.9.1

      - name: Set timezone

        run: |

          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

      - name: install pip packages

        run: |

          python -m pip install --upgrade pip

          pip3 install -r requirements.txt

      - name: weixin

        run: |

          python3 main.py

